### ISSUE TITLE
Can you help me to integrate the board

### ISSUE THREAD

**Issue by RoZelm0** [lora-aprs/LoRa_APRS_Tracker#120]
Can you help me to integrate the board 1.2 with axp2101

https://github.com/kizniche/ttgo-tbeam-ttn-tracker

**Comment by peterus** [comment]
The T-Beam v1.2 with AXP2101 is already supported. You need to select the correct board for compiling and flashing.

**Comment by RoZelm0** [comment]
are you sure that von (kizniche) is already finished??

It's not your link...
