### ISSUE TITLE
axp2101 wrong set for charging?

### ISSUE THREAD

**Issue by richonguzman** [lora-aprs/LoRa_APRS_Tracker#121]
Hi Peter,

line 150 or so:

should "_pmu->setChargerConstantCurr(XPOWERS_AXP192_CHG_CUR_780MA)" for AXP2101 be:

"_pmu->setChargerConstantCurr(XPOWERS_AXP2101_CHG_CUR_800MA);" ????

maybe this will affect some of your boards with this new code

**Comment by peterus** [comment]
thanks is fixed ;)
