### ISSUE TITLE
Course in between 1-360

### ISSUE THREAD

**Issue by dl9sau** [lora-aprs/LoRa_APRS_Tracker#23]
APRS spec sais, course should be in between 1 to 360.
I suppose gps.course.deg() returns 0 for north -> it should be assured, that 0 is changed to 360.

Since the course and speed fields are optional, a special case could be interesting to be dealt with:
if speed is 0 and course is zero, we are not moving. -> We can omit "000/000" in the aprs comment.

I would go this way:

```
                String course_and_speed = String("");
                int speed_int = (int)gps.speed.knots();
                if (speed_int > 0 && speed_int <= 999) {
                        String speed = padding(speed_int, 3);
                        int course_int = gps.course.deg();
                        /* course in between 1..360 due to aprs spec */
                        if (course_int == 0)
                                course_int = 360;
                        String course = padding(course_int, 3);
                        course_and_speed.concat(course + "/" + speed);
                } /* else: if speed is 0, course does not make sense, and is changing, even if we stand still */

```

Btw, I assure for the correct length (exactly, not mor. than 3 characters).
Speeds above 999 knods should be considered as bug, I think. But I'm not sure ;)

An assurance like above I added to the altitude field: better no altitude than non-sense ;)
```
                int speed_int = (int)gps.speed.knots();
                if (speed_int > 0 && speed_int <= 999) {
                        String speed = padding(speed_int, 3);
```

**Comment by peterus** [comment]
fixed with https://github.com/lora-aprs/LoRa_APRS_Tracker/commit/727c90eeae65a3d0668974cb6f507c4e9ecf07f3
