### ISSUE TITLE
I am missing a step for installation ?

### ISSUE THREAD

**Issue by zanco** [lora-aprs/LoRa_APRS_Tracker#26]
Hi, 
I have platform io installed on vscode and pointed to the folder .

The README.md states to change my configuration  in data/is-cfg.json

There is however only a tracker.json in the data folder.

The German instruction points to the igate installation and not the LoRa_APRS_Tracker

The French instruction mentions a settings.h in the src folder but there is no settings.h 

I am a bit stuck now.

![image](https://user-images.githubusercontent.com/4477734/116596665-f3416c80-a924-11eb-8aec-7bc0d2bfc87b.png)

Thanks for the help

**Comment by peterus** [comment]
@zanco you are right, the correct file is data/tracker.json. I will change the readme!

**Comment by peterus** [comment]
fixed in https://github.com/lora-aprs/LoRa_APRS_Tracker/commit/c16d6e43671a9d50a630c860b0de242884633462
