### ISSUE TITLE
GPS issue?

### ISSUE THREAD

**Issue by sm3ulc** [lora-aprs/LoRa_APRS_Tracker#30]
I get this after doing GPS-reset:

 **No GPS frames detected! Try to reset the GPS Chip with this firmware: https://github.com/lora-aprs/TTGO-T-Beam_GPS-reset**

Output from gps-reset:

$GPGSV,1,1,00*79
$GPGLL,,,,,,V,N*64
$GPRMC,,V,,,,,,,,,,N*53
$GPVTG,,,,,,,,,N*30
$GPGGA,,,,,,0,00,99.99,,,,,,*48
$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30

The output from gps-reset ok? Failed init in the tracker?

**Comment by DB2FM** [comment]
After performing the reset you must re-install the tracker-firmware.
(And for proper GPS-reception you should have free view to the sky ;) )

**Comment by sm3ulc** [comment]
Was a slightly faulty antenna.
