### ISSUE TITLE
Switch to alternative beacon message with middle button long press

### ISSUE THREAD

**Issue by tekk** [lora-aprs/LoRa_APRS_Tracker#45]
Hi,
I would love to have the ability to switch to an alternative message (and icon) when holding the middle button.
For example, I'm on a SOTA activation and when returning back I want another beacon message.
Or to switch between pedestrian and car, etc...
Since we have OneButton already included we could use **attachLongPressStop** to trigger between messages.
We could also have an array of messages (and icons) in the json config file and you would simply select the right message that currently suits your preference by holding the middle button.
Does this make any sense?
Waiting for your replies.
BTW I'm willing to help with the code.

**Comment by dl6nm** [comment]
I agree with you @tekk.

As a user I'd like to have an option for choosing another callsign/SSID, symbol/overlay and message. Maybe this could be definable in a `profiles` array or object in the `tracker.json` or one `tracker_{SSID}.json` for each `profile`.

**Comment by tekk** [comment]
I have implemented required changes in #47 
Please review and let me know.
73 OM7TEK

**Comment by peterus** [comment]
implemented in #47
