### ISSUE TITLE
 ttgo (20210222) t22_1.1 stuck in "INFO Smart Beacon is On"

### ISSUE THREAD

**Issue by AlarichvanDalen** [lora-aprs/LoRa_APRS_Tracker#46]
TTGO starts with the message
[Info] LoRa init done!
[Info] Smart Beacon is on.
After that, nothing happens. No beacon is sent.
The GPS LED flashes when the device is operated outside.
What ist to do?

**Comment by dl6nm** [comment]
I experienced the same behaviour. 
Setting the `debug` flag in `tracker.json` to `false` solved this for me.

**Comment by AlarichvanDalen** [comment]
> I experienced the same behaviour. Setting the `debug` flag in `tracker.json` to `false` solved this for me.
Thanks for the tip. Have tested both possible values. No change to the result.

**Comment by peterus** [comment]
@AlarichvanDalen @dl6nm please check the serial monitor. It looks like the gps chip has to be resetet. Upload this project and monitor the serial port until you see the nmea output. then re-upload the tracker firmware.
https://github.com/lora-aprs/TTGO-T-Beam_GPS-reset

**Comment by AlarichvanDalen** [comment]
I already thought that the GPS is not working properly. I followed the instructions. It looks like the board is now working fine. Thanks for the tip.
